#!/bin/bash

##############################################################################
## slightshow
##
## Copyright 2011 Johannes Marbach. All rights reserved.
## See the LICENSE file for details.

python2 Slightshow.py "$@"
