#!/bin/bash

##############################################################################
## slightshow
##
## Copyright 2011 Johannes Marbach. All rights reserved.
## See the LICENSE file for details.

dir=$(dirname "$0")
python2 "${dir}/Slightshow.py" "$@"
